/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_utte_fileseparatedemo_NDKFileUtils */

#ifndef _Included_com_utte_fileseparatedemo_NDKFileUtils
#define _Included_com_utte_fileseparatedemo_NDKFileUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_utte_fileseparatedemo_NDKFileUtils
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_utte_fileseparatedemo_NDKFileUtils_diff
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_utte_fileseparatedemo_NDKFileUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_utte_fileseparatedemo_NDKFileUtils_patch
  (JNIEnv *, jobject, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
